import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const websiteDir = path.resolve(import.meta.dir, '..');
const repoRoot = path.resolve(websiteDir, '..');
const sourceArchitecturePath = path.join(repoRoot, 'ARCHITECTURE.md');
const targetSharedDir = path.join(websiteDir, 'src', 'content', 'shared');
const targetArchitecturePath = path.join(targetSharedDir, 'architecture.md');

const generatedBanner = '<!-- Generated from ../ARCHITECTURE.md by bun run content:sync. Do not edit this file directly. -->\n\n';

await mkdir(targetSharedDir, { recursive: true });

try {
  await access(sourceArchitecturePath);
  const sourceContent = await readFile(sourceArchitecturePath, 'utf8');
  await writeFile(targetArchitecturePath, `${generatedBanner}${sourceContent}`);
} catch (error) {
  try {
    await access(targetArchitecturePath);
  } catch {
    throw new Error(
      `Shared architecture contract is missing. Expected either ${sourceArchitecturePath} or ${targetArchitecturePath}.`,
      { cause: error },
    );
  }
}
